FROM messense/rust-musl-cross:x86_64-musl
RUN rustup self update
RUN rustup set profile minimal
RUN rustup update stable --no-self-update
RUN rustup component add clippy rustfmt # Add common components
