* rust-musl-cross-docker-arch

This is an image based on [[https://github.com/rust-cross/rust-musl-cross][rust-musl-cross]], with tags renamed to =${RUST_VERSION}-${ARCH}= to make it easier to use when creating Docker images.
The image content is the same as rust-musl-cross; only the tags have been renamed.

It is intended to be used with a Dockerfile like the one below:

#+begin_src dockerfile
  ARG RUST_VERSION=latest

  FROM ghcr.io/typester/rust-musl-cross-docker-arch:$RUST_VERSION-$TARGETARCH AS builder

  COPY . .
  RUN cargo build --release --target ${RUST_MUSL_CROSS_TARGET}
#+end_src

Here is the [[https://github.com/typester/typester.dev/blob/main/Dockerfile][actual Dockerfile]] that I use.

** Notes

- Currently, it is set to build once a day.
- Supported arch: =linux/amd64=, =linux/arm64=
- The Rust version is the one provided by default in the rust-musl-cross image.
  You can update Rust within the Dockerfile using =rustup update=, but since they update the images relatively frequently, it seems fine to use the built-in version for now, as long as you're using the stable version.

** License

It is the same as rust-musl-cross. Please refer to the LICENSE* files.
