name: Push Pulled Rust Images to GHCR

on:
  workflow_dispatch:

jobs:
  pull_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [aarch64-musl, x86_64-musl]
        platform: [linux/arm64, linux/amd64]
    steps:
      # Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Pull the Docker image and get Rust version
      - name: Pull Docker image and get Rust version
        id: get_version
        run: |
          docker pull messense/rust-musl-cross:${{ matrix.tag }}
          RUST_VERSION=$(docker run --rm messense/rust-musl-cross:${{ matrix.tag }} rustc --version | awk '{print $2}')
          echo "RUST_VERSION=${RUST_VERSION}" >> $GITHUB_ENV

      # Retag and push the pulled image to GHCR
      - name: Tag and push image
        run: |
          docker tag messense/rust-musl-cross:${{ matrix.tag }} \
            ghcr.io/${{ github.repository_owner }}/rust-musl-cross-${{ matrix.tag }}:${{ env.RUST_VERSION }}
          docker buildx imagetools create \
            --tag ghcr.io/${{ github.repository_owner }}/rust-musl-cross-${{ matrix.tag }}:${{ env.RUST_VERSION }} \
            --platform ${{ matrix.platform }} \
            messense/rust-musl-cross:${{ matrix.tag }}
          docker push ghcr.io/${{ github.repository_owner }}/rust-musl-cross-${{ matrix.tag }}:${{ env.RUST_VERSION }}
