name: Push Pulled Rust Images to GHCR

on:
  workflow_dispatch:

jobs:
  pull_and_push:
    runs-on: ubuntu-latest

    steps:
      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Pull the Docker image and get Rust version
      - name: Pull Docker image and get Rust version
        id: get_version
        run: |
          docker pull messense/rust-musl-cross:x86_64-musl
          RUST_VERSION=$(docker run --rm messense/rust-musl-cross:x86_64-musl rustc --version | awk '{print $2}')
          echo "RUST_VERSION=${RUST_VERSION}" >> $GITHUB_ENV

      # Retag and push the pulled image to GHCR
      - name: Tag and push image
        run: |
          docker tag messense/rust-musl-cross:${{ matrix.tag }} ghcr.io/${{ github.repository_owner }}/rust-musl-cross-docker-arch:${{ env.RUST_VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/rust-musl-cross-docker-arch:${{ env.RUST_VERSION }}
